#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
=============================================================================
PoPu real-data reader — turn downloaded real mattress data into trainable
pressure maps
=============================================================================

[What does this file do?]

The project previously used "synthetic data" (generated by math formulas). Now
that we have the PoPu real dataset, this file reads it in, cleans it, and turns
it into the same format as the synthetic data: a "pressure map" flattened into a
string of numbers + a "pose label".

[What does the PoPu data look like? (pitfalls noted here)]

  - Layout: pupu_data/PoPu_data/sensomatt_data/<volunteer id>/<pose><index>_<variant>.json
    60 volunteers in total (folders 1~60), 86 files per person.
  - Each JSON contains: volunteer_id / sex / height / weight /
    sensomatt_columns=6 / sensomatt_rows=12 / position / variation / snapshots
  - snapshots is a dict whose keys are '0'~'9' (strings); each value is one frame:
        {'id': ..., 'sensomatt_readings': [72 numbers]}
    72 = 12 rows × 6 columns; the first 6 are row 1, the next 6 are row 2, ... (row-major)
  - The pose is parsed from the "filename", not the position field (others files have position=None).
    supine=supine  left=left side  right=right side  prone=prone
    There are also empty (unloaded, nobody lying down) and others (other poses, excluded here).

[The most critical step: baseline subtraction (zero-point calibration)]

The numbers read directly are "raw readings"; even with nobody lying down there is
a "fake value" of about 482 (zero offset). A person pressing down only raises the
reading by 0~12 — the signal is weak and completely drowned by that 482.

So each volunteer has 1 empty file (10 unloaded frames); we average them into a
"baseline" and subtract it from every reading, which is what makes the body shape
actually show up. This is the "zero-point calibration" — the first trick in the
calibration chain — applied for real on real data.

[How to distinguish the four poses? (look at shape, not amplitude)]

  Supine: bright in the middle, left-right symmetric (lying flat, shoulders/hips press the middle)
  Left side: bright region shifted left (lying on the left side, pressing the left half)
  Right side: bright region shifted right
  Prone: large uniformly bright region (chest/abdomen in broad contact with the bed)

=============================================================================
"""

import json
import os
import glob

import numpy as np


# ============================================================================
# 1. Constants: pose order, normalization, data directory
# ============================================================================

# Order of the four poses (labels 0/1/2/3 map to this order). Fixed and shared by training and prediction.
POSE_ORDER = ["supine", "left", "right", "prone"]

# Display labels (used for plotting and printing)
POSE_LABELS_CN = {
    "supine": "Supine",
    "left": "Left side",
    "right": "Right side",
    "prone": "Prone",
}

# English names (used in README / paper figures)
POSE_LABELS_EN = {
    "supine": "Supine",
    "left": "Left",
    "right": "Right",
    "prone": "Prone",
}

# Default data location (relative to the project root)
DEFAULT_DATA_DIR = "pupu_data/PoPu_data/sensomatt_data"

# Normalization basis: after baseline subtraction the signal is roughly -2 ~ +12;
# dividing by 20 brings it into 0~0.6. Same idea as the /200 used for synthetic
# data: shrink the numbers so neural network training stays stable.
SCALE = 20.0

# Sensor array dimensions (PoPu's SensoMatt is 12 rows × 6 cols = 72 points)
GRID_ROWS = 12
GRID_COLS = 6


# ============================================================================
# 2. Low-level reading: a single file
# ============================================================================

def parse_pose(filename):
    """
    Parse the pose label from a filename. Filenames look like:
        supine1_0.json  → "supine"
        left3_1.json    → "left"
        right5_2.json   → "right"
        prone2_0.json   → "prone"
        empty1.json     → "empty" (unloaded, not a pose)
        others1.json    → "others" (other poses, excluded)

    Why not use the position field inside the JSON? Because others files have
    position=None, whereas the filename is always reliable. The filename is the
    "ground truth".
    """
    # Take the letter run before the first underscore or digit
    prefix = ""
    for ch in filename:
        if ch.isalpha():
            prefix += ch
        else:
            break
    return prefix.lower()


def load_snapshots(path):
    """
    Read a JSON file and return all of its "frames".

    Returns:
      matrices —— list, each element a (12, 6) pressure map (raw readings, no baseline subtraction)
      meta     —— dict, volunteer height/weight and other metadata
    """
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # snapshots keys are strings '0'~'9'; sort numerically so frame order is correct
    keys = sorted(data["snapshots"].keys(), key=int)
    matrices = []
    for k in keys:
        readings = data["snapshots"][k]["sensomatt_readings"]
        # Real data occasionally has "dirty frames": readings that are not 72
        # values (missing 1~2). Skip these — they are under 0.04%, and forcibly
        # padding them would inject fake data.
        if len(readings) != GRID_ROWS * GRID_COLS:
            continue
        # 72 numbers → 12 rows × 6 cols (row-major: the first 6 are row 1)
        matrices.append(np.asarray(readings, dtype=float).reshape(GRID_ROWS, GRID_COLS))

    meta = {
        "volunteer_id": data.get("volunteer_id"),
        "sex": data.get("sex"),
        "height": data.get("height"),
        "weight": data.get("weight"),
        "position": data.get("position"),
    }
    return matrices, meta


def load_baseline(vol_dir):
    """
    Read a volunteer's "unloaded baseline": average the frames of the empty file.

    Why average? Unloaded readings have noise too; averaging several frames damps
    out random jitter and yields a "zero point" closer to the true value.

    Returns: a (12, 6) baseline map. If the volunteer has no empty file, returns all zeros.
    """
    empties = sorted(glob.glob(os.path.join(vol_dir, "empty*.json")))
    if not empties:
        return np.zeros((GRID_ROWS, GRID_COLS))

    matrices, _ = load_snapshots(empties[0])
    # Stack all frames and average → one stable baseline
    return np.mean(np.stack(matrices), axis=0)


# ============================================================================
# 3. Core: read the whole dataset into (samples, labels)
# ============================================================================

def load_dataset(data_dir=DEFAULT_DATA_DIR, frames_per_file=1, seed=0,
                 shuffle=True):
    """
    Iterate over all 60 volunteers and read the four poses into a "training dataset".

    Pipeline (same for every volunteer):
      1. Read the empty file and compute the baseline (this volunteer's "zero point")
      2. Iterate over pose files (starting with supine/left/right/prone, excluding empty/others)
      3. Subtract the baseline from each frame's readings → the "cleaned" pressure signal
      4. Flatten to 72 numbers + normalize, paired with the pose label

    Args:
      data_dir        —— data directory
      frames_per_file —— how many frames to take per file as samples (default 1, first frame).
                         Each file usually has 10 frames; taking 1 gives 1260 samples/class.
      seed            —— random seed for shuffling
      shuffle         —— whether to shuffle

    Returns:
      X       —— (num samples, 72) 2D array, baseline-subtracted and normalized
      y       —— (num samples,) class ids (0=supine/1=left/2=right/3=prone)
      classes —— pose-name list ["supine","left","right","prone"]
      meta    —— per-sample metadata list (volunteer, height/weight, etc.), aligned with X
    """
    # Volunteer folders (sorted numerically, 1~60)
    vol_dirs = sorted(
        [d for d in glob.glob(os.path.join(data_dir, "*")) if os.path.isdir(d)],
        key=lambda p: int(os.path.basename(p)) if os.path.basename(p).isdigit() else 999999,
    )

    X_list, y_list, meta_list = [], [], []

    for vol_dir in vol_dirs:
        baseline = load_baseline(vol_dir)   # this volunteer's zero point

        for path in sorted(glob.glob(os.path.join(vol_dir, "*.json"))):
            filename = os.path.basename(path)
            pose = parse_pose(filename)
            if pose not in POSE_ORDER:       # exclude empty / others
                continue

            matrices, meta = load_snapshots(path)
            # Take the first frames_per_file frames as samples (each frame = one independent measurement)
            for mat in matrices[:frames_per_file]:
                signal = mat - baseline          # subtract baseline = zero-point calibration
                X_list.append(signal.ravel())    # flatten 12×6 to 72
                y_list.append(POSE_ORDER.index(pose))
                meta_list.append(meta)

    X = np.array(X_list, dtype=float) / SCALE   # normalize
    y = np.array(y_list, dtype=int)

    if shuffle:
        rng = np.random.default_rng(seed)
        idx = rng.permutation(len(X))
        X, y = X[idx], y[idx]
        meta_list = [meta_list[i] for i in idx]

    return X, y, list(POSE_ORDER), meta_list


def split_train_test(X, y, test_ratio=0.2, seed=0):
    """
    Split into a "training set" and an "exam paper". Testing on unseen data keeps the score honest.
    """
    rng = np.random.default_rng(seed)
    idx = rng.permutation(len(X))
    n_test = int(len(X) * test_ratio)
    test_idx, train_idx = idx[:n_test], idx[n_test:]
    return X[train_idx], y[train_idx], X[test_idx], y[test_idx]


def split_by_volunteer(X, y, meta, test_ratio=0.2, seed=0):
    """
    Split by "volunteer": some people train, others take the exam.

    Why is it needed? — split_train_test splits samples randomly, so one person's
    data may end up half in training and half in testing; the model effectively
    "has seen this person", inflating the score. Splitting by person makes the
    test set full of strangers the model has never seen — that is the true
    performance of a real deployment (a new user buys it home and the model has
    never seen them).

    Returns: X_train, y_train, X_test, y_test
    """
    vol = np.array([int(m["volunteer_id"]) for m in meta])
    rng = np.random.default_rng(seed)
    vols = np.unique(vol)
    rng.shuffle(vols)
    n_test_v = int(len(vols) * test_ratio)
    test_v = set(vols[:n_test_v])
    te = np.array([v in test_v for v in vol])
    tr = ~te
    return X[tr], y[tr], X[te], y[te]
