#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
=============================================================================
Sleep-pose classification training script — train this project's first "real model"
=============================================================================

What does it do?

Feed the 600 pressure maps generated by the sleep-pose dataset generator into
the mini neural network, and train it to distinguish the three sleep postures
(supine/side/prone).

Training produces two outputs:
  1. An accuracy number in the terminal (the score on the exam set)
  2. outputs/pose_training.png (loss curve + confusion matrix)

What is a confusion matrix?

A 3×3 table where rows are the "true posture" and columns are "the posture the
model guessed". The diagonal (correct guesses) should be as large as possible;
the off-diagonal shows "what the model confuses with what". Medical AI uses it
to evaluate models instead of a blanket "accuracy" — because you need to know
where the mistakes are.

How to run:

    python3 src/train_pose_classifier.py

=============================================================================
"""

import argparse
import logging
import os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

plt.rcParams["font.sans-serif"] = ["PingFang SC", "Arial Unicode MS", "Heiti SC"]
plt.rcParams["axes.unicode_minus"] = False

from sensor_config import GRID_W, GRID_H, POSE_NAMES, POSE_LABELS_CN, OUT_DIR
from pose_dataset import generate_dataset, split_train_test
from mlp import TinyMLP
from verdict import render_pose_verdict


# ---- Training hyperparameter defaults (no need to edit code; pass via CLI, see bottom of file) ----
N_PER_CLASS = 200     # 200 samples per posture, 600 total
N_HIDDEN = 32         # 32 hidden neurons
N_EPOCH = 300         # pass over the whole dataset 300 times
BATCH = 32            # feed 32 samples at a time (learn in small bites, more stable than one gulp)
LR = 0.5              # learning rate: how big a step each weight takes
SEED = 0              # fixed random seed, reproducible across runs


def main(n_per_class=N_PER_CLASS, n_hidden=N_HIDDEN, n_epoch=N_EPOCH,
         batch=BATCH, lr=LR, seed=SEED):
    print("=" * 62)
    print(" Sleep-pose classification: train this project's first real model")
    print("=" * 62)
    print()

    # ---- 1. generate data + split ----
    X, y, classes = generate_dataset(n_per_class, seed=seed)
    X_train, y_train, X_test, y_test = split_train_test(X, y, test_ratio=0.2, seed=seed)
    logging.info("Dataset generated: %d training samples + %d test samples", len(X_train), len(X_test))
    print(f"      Three postures: supine(0) / side(1) / prone(2)")

    # ---- 2. build the network ----
    model = TinyMLP(n_input=GRID_W * GRID_H, n_hidden=n_hidden,
                    n_output=len(classes), seed=seed)
    logging.info("Network built: %d → %d (hidden) → %d (three postures)",
                 GRID_W * GRID_H, n_hidden, len(classes))

    # ---- 3. train ----
    losses, train_accs = [], []
    rng = np.random.default_rng(seed)
    n = len(X_train)

    for epoch in range(n_epoch):
        # shuffle then split into mini-batches (avoid the network "memorizing in order")
        idx = rng.permutation(n)
        epoch_loss = 0.0
        for start in range(0, n, batch):
            batch_idx = idx[start:start + batch]
            epoch_loss += model.train_step(X_train[batch_idx], y_train[batch_idx], lr=lr)
        epoch_loss /= (n // batch + 1)

        losses.append(epoch_loss)
        train_accs.append(model.accuracy(X_train, y_train))

        # report progress every 50 epochs so you can see it "learning" (via logging, with timestamps)
        if (epoch + 1) % 50 == 0:
            logging.info("Epoch %3d: loss %.4f, training accuracy %.1f%%",
                         epoch + 1, epoch_loss, train_accs[-1] * 100)

    # ---- 4. exam (data the model has never seen) ----
    test_acc = model.accuracy(X_test, y_test)
    print(f"[4/4] Exam result ({len(X_test)} never-seen samples): {test_acc*100:.1f}%")

    # per-class accuracy + confusion matrix
    preds = model.predict(X_test)
    print()
    print("      Per-class accuracy:")
    cm = np.zeros((len(classes), len(classes)), dtype=int)   # confusion matrix
    for true, pred in zip(y_test, preds):
        cm[true, pred] += 1
    for i, cls in enumerate(classes):
        correct = cm[i, i]
        total = cm[i].sum()
        cn = POSE_LABELS_CN[cls]
        print(f"        {cn}({cls:>6}): {correct}/{total} = {correct/total*100:.0f}%")

    print()
    print("      Confusion matrix (rows=true, columns=predicted, diagonal=correct):")
    header = "                " + "  ".join(f"{POSE_LABELS_CN[c]:>4}" for c in classes)
    print(header)
    for i, cls in enumerate(classes):
        row = "  ".join(f"{v:>4}" for v in cm[i])
        print(f"        true {POSE_LABELS_CN[cls]:<4} {row}")

    # ---- plot: loss curve + confusion matrix ----
    plot(losses, train_accs, cm, classes, test_acc)

    # ==================================================================
    # Extra experiment: do sensor flaws actually hurt the classification model? (a real test; counterintuitive result)
    # ==================================================================
    # Run the exam set through a "bad sensor": per-point sensitivity flaw + fake
    # baseline + heavy crosstalk, then clean it back up with the calibration
    # toolkit and watch the accuracy change.
    print()
    print("=" * 62)
    print(" Extra experiment: sensor flaws vs calibration rescue (measured)")
    print("=" * 62)

    from calibration import correct_crosstalk

    def apply_crosstalk(img, c):
        """Add crosstalk to one image (consistent with the forward model in the calibration toolkit)."""
        padded = np.pad(img, 1, mode="edge")
        nb = (padded[:-2, 1:-1] + padded[2:, 1:-1] +
              padded[1:-1, :-2] + padded[1:-1, 2:]) / 4.0
        return (1 - c) * img + c * nb

    rng_imp = np.random.default_rng(seed + 99)
    pixel_gain = rng_imp.uniform(0.5, 1.5, size=(1, GRID_W * GRID_H))  # per-point sensitivity
    pixel_offset = rng_imp.uniform(0.02, 0.15, size=(1, GRID_W * GRID_H))  # fake baseline
    C_HEAVY = 0.3   # heavy crosstalk (real products ~0.1; amplified here to show the damage)

    def to_dirty(X):
        """Clean data → bad-sensor readings."""
        out = X * pixel_gain + pixel_offset
        return np.array([apply_crosstalk(x.reshape(GRID_H, GRID_W), C_HEAVY).ravel()
                         for x in out])

    def to_rescued(Xd):
        """Bad readings → calibration wash (known calibration params: subtract baseline, divide gain, undo crosstalk)."""
        out = (Xd - pixel_offset) / pixel_gain
        return np.array([correct_crosstalk(x.reshape(GRID_H, GRID_W), C_HEAVY).ravel()
                         for x in out])

    X_dirty = to_dirty(X_test)
    X_rescued = to_rescued(X_dirty)
    acc_dirty = model.accuracy(X_dirty, y_test)
    acc_rescued = model.accuracy(X_rescued, y_test)
    print(f"  Clean data exam                       : {test_acc*100:.1f}%")
    print(f"  Bad-sensor exam (gain+baseline+crosstalk): {acc_dirty*100:.1f}%")
    print(f"  After calibration wash                 : {acc_rescued*100:.1f}%")

    # ---- dynamic verdict: the program speaks for itself based on the numbers above, nothing hardcoded ----
    # Here we call the verdict generator render_pose_verdict: it takes test_acc /
    # acc_dirty / acc_rescued, applies the decision rules, and generates what to
    # say this time. Change the numbers and the verdict changes — no more
    # "numbers collapsed but still claiming robust" nonsense.
    print()
    print(" Verdict for this experiment (auto-generated from the numbers above, not hardcoded):")
    print()
    for line in render_pose_verdict(test_acc, acc_dirty, acc_rescued):
        print("   " + line)
    print()
    # The following is "background knowledge" — a fixed explanation, not the verdict
    # for this experiment. It explains "why the phenomenon above happens" and is
    # number-independent, so it can be hardcoded; but it is clearly labeled as
    # knowledge, not a conclusion.
    print(" PS · Background knowledge (fixed explanation, not this experiment's verdict):")
    print("   The three postures differ a lot in 'shape' (side lying to one side vs supine centered),")
    print("   so the model classifies mainly by 'where it lights up', not by 'how bright' (magnitude) —")
    print("   which is why it's naturally immune to magnitude flaws (gain, baseline).")
    print("   But calibration is irreplaceable in tasks that read absolute pressure: in pressure-ulcer")
    print("   alerts, tissue under >32 mmHg for long is at risk of ischemic damage; a +30% gain drift")
    print("   turns a safe 25 mmHg into a dangerous 32.5 mmHg. Classification can tolerate flaws,")
    print("   quantitative tasks cannot — that's where calibration earns its keep.")


def plot(losses, train_accs, cm, classes, test_acc):
    os.makedirs(OUT_DIR, exist_ok=True)
    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    # left: loss curve (lower is better)
    ax = axes[0]
    ax.plot(losses, color="tab:blue", label="Loss (how far off)")
    ax.set_xlabel("Epoch")
    ax.set_ylabel("Loss")
    ax.set_title("Training: loss dropping = learning better")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # right: confusion matrix heatmap
    ax = axes[1]
    im = ax.imshow(cm, cmap="Blues")
    ax.set_xticks(range(len(classes)))
    ax.set_yticks(range(len(classes)))
    ax.set_xticklabels([POSE_LABELS_CN[c] for c in classes])
    ax.set_yticklabels([POSE_LABELS_CN[c] for c in classes])
    ax.set_xlabel("Predicted")
    ax.set_ylabel("True posture")
    ax.set_title(f"Confusion matrix (test accuracy {test_acc*100:.1f}%)")
    # fill in the numbers inside the cells
    for i in range(len(classes)):
        for j in range(len(classes)):
            ax.text(j, i, str(cm[i, j]), ha="center", va="center",
                    color="white" if cm[i, j] > cm.max() / 2 else "black")

    plt.tight_layout()
    path = os.path.join(OUT_DIR, "pose_training.png")
    plt.savefig(path, dpi=120, bbox_inches="tight")
    plt.close(fig)
    print(f"\n Figure saved: {path}")


if __name__ == "__main__":
    # ---- CLI args: tune without editing code ----
    # e.g. python3 src/train_pose_classifier.py --epochs 100 --lr 0.3
    parser = argparse.ArgumentParser(
        description="Train a sleep-pose classifier (supine/side/prone)")
    parser.add_argument("--n-per-class", type=int, default=N_PER_CLASS,
                        help=f"Samples per posture (default {N_PER_CLASS})")
    parser.add_argument("--epochs", type=int, default=N_EPOCH,
                        help=f"Number of epochs (default {N_EPOCH})")
    parser.add_argument("--batch", type=int, default=BATCH,
                        help=f"Batch size (default {BATCH})")
    parser.add_argument("--lr", type=float, default=LR,
                        help=f"Learning rate (default {LR})")
    parser.add_argument("--seed", type=int, default=SEED,
                        help=f"Random seed (default {SEED}, fixed for reproducibility)")
    args = parser.parse_args()

    # ---- logging: standard progress output with timestamps (engineering-practice demo) ----
    logging.basicConfig(level=logging.INFO,
                        format="[%(asctime)s] %(message)s", datefmt="%H:%M:%S")
    main(n_per_class=args.n_per_class, n_epoch=args.epochs,
         batch=args.batch, lr=args.lr, seed=args.seed)
